name: Deploy & Purge Cloudflare Cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Trigger Vercel Deploy
        run: |
          echo "Triggering Vercel deployment..."
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_S2oLxGOx61q6RR4gO4u6qBYJrdK1/Ad8AB5DP7l"

      - name: ⏳ Wait for deployment to finish
        run: |
          echo "Waiting 3 minutes for Vercel deployment to complete..."
          sleep 180

      - name: 🔥 Purge Cloudflare Cache
        run: |
          echo "Purging Cloudflare cache..."
          response=$(curl -s -w "\n%{http_code}" -X POST "https://blog.moydus.com/api/purge-cloudflare")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)

          echo "HTTP Status: $http_code"
          echo "Response: $body"

          # Check if request succeeded (200 OK)
          if [ "$http_code" = "200" ]; then
            echo "✅ Cloudflare cache purge request successful!"
          else
            echo "⚠️  Cache purge returned status $http_code"
            echo "Note: This is non-critical, deployment succeeded"
            # Don't fail the workflow for cache purge issues
          fi

      - name: ✅ Deployment Complete
        run: |
          echo "🎉 Deployment and cache purge completed successfully!"
          echo "Site: https://blog.moydus.com"
